package Aeropuerto;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * El código siguiente define una clase llamada "Login"
 * @author Diego
 */
public class Login extends javax.swing.JDialog {

    /**
     * Nombre de usuario para la conexión a la base de datos.
     */
    private String USER = "";
    /**
     * Contraseña para la conexión a la base de datos.
     */
    private String PASS = "";
    
    /**
     * Crea una nueva instancia de la ventana de inicio de sesión.
     *
     * @param parent El componente padre de la ventana.
     * @param modal  Especifica si la ventana es modal o no.
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_IniciarSesion = new javax.swing.JButton();
        tf_User = new javax.swing.JTextField();
        pf_Pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_IniciarSesion.setText("Ingresar");
        btn_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IniciarSesionActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jLabel3.setText("LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_IniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addComponent(tf_User)
                        .addComponent(pf_Pass))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btn_IniciarSesion)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se ejecuta al hacer clic en el botón de iniciar sesión. 
     * Obtiene el usuario y la contraseña ingresados, realiza una lógica de validación
     * y muestra un mensaje de bienvenida o de usuario no existente.
     *
     * @param evt Evento de acción generado al hacer clic en el botón.
     */
    private void btn_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IniciarSesionActionPerformed
        // Obtiene el usuario y la contraseña ingresados en los campos de texto
        String usuario = tf_User.getText();
        String contrasena = new String(pf_Pass.getPassword());

        // Lógica de validación de credenciales
        if (usuario.equals("postgres") && contrasena.equals("postgres")) {
            JOptionPane.showMessageDialog(this, "¡Bienvenido postgres!");
            USER = usuario;
            PASS = contrasena;
            this.dispose();
        } else if (usuario.equals("administrador") && contrasena.equals("232323ADM")) {
            JOptionPane.showMessageDialog(this, "¡Bienvenido administrador!");
            USER = usuario;
            PASS = contrasena;
            this.dispose();
        } else if (usuario.equals("aerolinea_staff") && contrasena.equals("235491AERS")) {
            JOptionPane.showMessageDialog(this, "¡Bienvenido aerolinea_staff!");
            USER = usuario;
            PASS = contrasena;
            this.dispose();
        } else if (usuario.equals("pasajero_service") && contrasena.equals("094312PASER")) {
            JOptionPane.showMessageDialog(this, "¡Bienvenido pasajero_service!");
            USER = usuario;
            PASS = contrasena;
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no existente");
            USER = "";
            PASS = "";
            this.dispose();
        }
    }//GEN-LAST:event_btn_IniciarSesionActionPerformed

    /**
     * Método que devuelve el nombre de usuario almacenado.
     *
     * @return Nombre de usuario.
     */
    String getUsr() {
        return USER;
    }

    /**
     * Método que devuelve la contraseña almacenada.
     *
     * @return Contraseña.
     */
    String getPass() {
        return PASS;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Login login = new Login(new javax.swing.JFrame(), true); // Pasa la referencia del frame y true para indicar que sea modal
            login.setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_IniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pf_Pass;
    private javax.swing.JTextField tf_User;
    // End of variables declaration//GEN-END:variables

}
